# -*- coding: utf-8 -*-

'''Opus constants.'''

from __future__ import unicode_literals, absolute_import

__all__ = [
        'OK',
        'BAD_ARG',
        'BUFFER_TOO_SMALL',
        'INTERNAL_ERROR',
        'INVALID_PACKET',
        'UNIMPLEMENTED',
        'INVALID_STATE',
        'ALLOC_FAIL',
        'SET_APPLICATION_REQUEST',
        'GET_APPLICATION_REQUEST',
        'SET_BITRATE_REQUEST',
        'GET_BITRATE_REQUEST',
        'SET_MAX_BANDWIDTH_REQUEST',
        'GET_MAX_BANDWIDTH_REQUEST',
        'SET_VBR_REQUEST',
        'GET_VBR_REQUEST',
        'SET_BANDWIDTH_REQUEST',
        'GET_BANDWIDTH_REQUEST',
        'SET_COMPLEXITY_REQUEST',
        'GET_COMPLEXITY_REQUEST',
        'SET_INBAND_FEC_REQUEST',
        'GET_INBAND_FEC_REQUEST',
        'SET_PACKET_LOSS_PERC_REQUEST',
        'GET_PACKET_LOSS_PERC_REQUEST',
        'SET_DTX_REQUEST',
        'GET_DTX_REQUEST',
        'SET_VBR_CONSTRAINT_REQUEST',
        'GET_VBR_CONSTRAINT_REQUEST',
        'SET_FORCE_CHANNELS_REQUEST',
        'GET_FORCE_CHANNELS_REQUEST',
        'SET_SIGNAL_REQUEST',
        'GET_SIGNAL_REQUEST',
        'GET_LOOKAHEAD_REQUEST',
        'GET_SAMPLE_RATE_REQUEST',
        'GET_FINAL_RANGE_REQUEST',
        'GET_PITCH_REQUEST',
        'SET_GAIN_REQUEST',
        'GET_GAIN_REQUEST',
        'SET_LSB_DEPTH_REQUEST',
        'GET_LSB_DEPTH_REQUEST',
        'GET_LAST_PACKET_DURATION_REQUEST',
        'SET_EXPERT_FRAME_DURATION_REQUEST',
        'GET_EXPERT_FRAME_DURATION_REQUEST',
        'SET_PREDICTION_DISABLED_REQUEST',
        'GET_PREDICTION_DISABLED_REQUEST',
        'AUTO',
        'BITRATE_MAX',
        'APPLICATION_VOIP',
        'APPLICATION_AUDIO',
        'APPLICATION_RESTRICTED_LOWDELAY',
        'SIGNAL_VOICE',
        'SIGNAL_MUSIC',
        'BANDWIDTH_NARROWBAND',
        'BANDWIDTH_MEDIUMBAND',
        'BANDWIDTH_WIDEBAND',
        'BANDWIDTH_SUPERWIDEBAND',
        'BANDWIDTH_FULLBAND',
        'FRAMESIZE_ARG',
        'FRAMESIZE_2_5_MS',
        'FRAMESIZE_5_MS',
        'FRAMESIZE_10_MS',
        'FRAMESIZE_20_MS',
        'FRAMESIZE_40_MS',
        'FRAMESIZE_60_MS',
        'RESET_STATE',
        ]

from .binding import C


OK = C.OPUS_OK
BAD_ARG = C.OPUS_BAD_ARG
BUFFER_TOO_SMALL = C.OPUS_BUFFER_TOO_SMALL
INTERNAL_ERROR = C.OPUS_INTERNAL_ERROR
INVALID_PACKET = C.OPUS_INVALID_PACKET
UNIMPLEMENTED = C.OPUS_UNIMPLEMENTED
INVALID_STATE = C.OPUS_INVALID_STATE
ALLOC_FAIL = C.OPUS_ALLOC_FAIL

SET_APPLICATION_REQUEST = C.OPUS_SET_APPLICATION_REQUEST
GET_APPLICATION_REQUEST = C.OPUS_GET_APPLICATION_REQUEST
SET_BITRATE_REQUEST = C.OPUS_SET_BITRATE_REQUEST
GET_BITRATE_REQUEST = C.OPUS_GET_BITRATE_REQUEST
SET_MAX_BANDWIDTH_REQUEST = C.OPUS_SET_MAX_BANDWIDTH_REQUEST
GET_MAX_BANDWIDTH_REQUEST = C.OPUS_GET_MAX_BANDWIDTH_REQUEST
SET_VBR_REQUEST = C.OPUS_SET_VBR_REQUEST
GET_VBR_REQUEST = C.OPUS_GET_VBR_REQUEST
SET_BANDWIDTH_REQUEST = C.OPUS_SET_BANDWIDTH_REQUEST
GET_BANDWIDTH_REQUEST = C.OPUS_GET_BANDWIDTH_REQUEST
SET_COMPLEXITY_REQUEST = C.OPUS_SET_COMPLEXITY_REQUEST
GET_COMPLEXITY_REQUEST = C.OPUS_GET_COMPLEXITY_REQUEST
SET_INBAND_FEC_REQUEST = C.OPUS_SET_INBAND_FEC_REQUEST
GET_INBAND_FEC_REQUEST = C.OPUS_GET_INBAND_FEC_REQUEST
SET_PACKET_LOSS_PERC_REQUEST = C.OPUS_SET_PACKET_LOSS_PERC_REQUEST
GET_PACKET_LOSS_PERC_REQUEST = C.OPUS_GET_PACKET_LOSS_PERC_REQUEST
SET_DTX_REQUEST = C.OPUS_SET_DTX_REQUEST
GET_DTX_REQUEST = C.OPUS_GET_DTX_REQUEST
SET_VBR_CONSTRAINT_REQUEST = C.OPUS_SET_VBR_CONSTRAINT_REQUEST
GET_VBR_CONSTRAINT_REQUEST = C.OPUS_GET_VBR_CONSTRAINT_REQUEST
SET_FORCE_CHANNELS_REQUEST = C.OPUS_SET_FORCE_CHANNELS_REQUEST
GET_FORCE_CHANNELS_REQUEST = C.OPUS_GET_FORCE_CHANNELS_REQUEST
SET_SIGNAL_REQUEST = C.OPUS_SET_SIGNAL_REQUEST
GET_SIGNAL_REQUEST = C.OPUS_GET_SIGNAL_REQUEST
GET_LOOKAHEAD_REQUEST = C.OPUS_GET_LOOKAHEAD_REQUEST
GET_SAMPLE_RATE_REQUEST = C.OPUS_GET_SAMPLE_RATE_REQUEST
GET_FINAL_RANGE_REQUEST = C.OPUS_GET_FINAL_RANGE_REQUEST
GET_PITCH_REQUEST = C.OPUS_GET_PITCH_REQUEST
SET_GAIN_REQUEST = C.OPUS_SET_GAIN_REQUEST
GET_GAIN_REQUEST = C.OPUS_GET_GAIN_REQUEST
SET_LSB_DEPTH_REQUEST = C.OPUS_SET_LSB_DEPTH_REQUEST
GET_LSB_DEPTH_REQUEST = C.OPUS_GET_LSB_DEPTH_REQUEST
GET_LAST_PACKET_DURATION_REQUEST = C.OPUS_GET_LAST_PACKET_DURATION_REQUEST
SET_EXPERT_FRAME_DURATION_REQUEST = C.OPUS_SET_EXPERT_FRAME_DURATION_REQUEST
GET_EXPERT_FRAME_DURATION_REQUEST = C.OPUS_GET_EXPERT_FRAME_DURATION_REQUEST
SET_PREDICTION_DISABLED_REQUEST = C.OPUS_SET_PREDICTION_DISABLED_REQUEST
GET_PREDICTION_DISABLED_REQUEST = C.OPUS_GET_PREDICTION_DISABLED_REQUEST

AUTO = C.OPUS_AUTO
BITRATE_MAX = C.OPUS_BITRATE_MAX

APPLICATION_VOIP = C.OPUS_APPLICATION_VOIP
APPLICATION_AUDIO = C.OPUS_APPLICATION_AUDIO
APPLICATION_RESTRICTED_LOWDELAY = C.OPUS_APPLICATION_RESTRICTED_LOWDELAY

SIGNAL_VOICE = C.OPUS_SIGNAL_VOICE
SIGNAL_MUSIC = C.OPUS_SIGNAL_MUSIC
BANDWIDTH_NARROWBAND = C.OPUS_BANDWIDTH_NARROWBAND
BANDWIDTH_MEDIUMBAND = C.OPUS_BANDWIDTH_MEDIUMBAND
BANDWIDTH_WIDEBAND = C.OPUS_BANDWIDTH_WIDEBAND
BANDWIDTH_SUPERWIDEBAND = C.OPUS_BANDWIDTH_SUPERWIDEBAND
BANDWIDTH_FULLBAND = C.OPUS_BANDWIDTH_FULLBAND

FRAMESIZE_ARG = C.OPUS_FRAMESIZE_ARG
FRAMESIZE_2_5_MS = C.OPUS_FRAMESIZE_2_5_MS
FRAMESIZE_5_MS = C.OPUS_FRAMESIZE_5_MS
FRAMESIZE_10_MS = C.OPUS_FRAMESIZE_10_MS
FRAMESIZE_20_MS = C.OPUS_FRAMESIZE_20_MS
FRAMESIZE_40_MS = C.OPUS_FRAMESIZE_40_MS
FRAMESIZE_60_MS = C.OPUS_FRAMESIZE_60_MS

RESET_STATE = C.OPUS_RESET_STATE


# vim:set ai et ts=4 sw=4 sts=4 fenc=utf-8:
